//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportSQL.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Output : global::System.Configuration.ApplicationSettingsBase {
        
        private static Output defaultInstance = ((Output)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Output())));
        
        public static Output Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Functions")]
        public string DirectoryName_Functions {
            get {
                return ((string)(this["DirectoryName_Functions"]));
            }
            set {
                this["DirectoryName_Functions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Procedures")]
        public string DirectoryName_Procedures {
            get {
                return ((string)(this["DirectoryName_Procedures"]));
            }
            set {
                this["DirectoryName_Procedures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Triggers")]
        public string DirectoryName_Triggers {
            get {
                return ((string)(this["DirectoryName_Triggers"]));
            }
            set {
                this["DirectoryName_Triggers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Views")]
        public string DirectoryName_Views {
            get {
                return ((string)(this["DirectoryName_Views"]));
            }
            set {
                this["DirectoryName_Views"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Functions.fnc")]
        public string FileName_FunctionsType {
            get {
                return ((string)(this["FileName_FunctionsType"]));
            }
            set {
                this["FileName_FunctionsType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Procedures.prc")]
        public string FileName_ProceduresType {
            get {
                return ((string)(this["FileName_ProceduresType"]));
            }
            set {
                this["FileName_ProceduresType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Triggers.trg")]
        public string FileName_TriggersType {
            get {
                return ((string)(this["FileName_TriggersType"]));
            }
            set {
                this["FileName_TriggersType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Views.vw")]
        public string FileName_ViewsType {
            get {
                return ((string)(this["FileName_ViewsType"]));
            }
            set {
                this["FileName_ViewsType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ExportSQL.sql")]
        public string FileName_SingleFile {
            get {
                return ((string)(this["FileName_SingleFile"]));
            }
            set {
                this["FileName_SingleFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("End of file")]
        public string TextEndOfFile {
            get {
                return ((string)(this["TextEndOfFile"]));
            }
            set {
                this["TextEndOfFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Elenco Funzioni")]
        public string TitleFunctions {
            get {
                return ((string)(this["TitleFunctions"]));
            }
            set {
                this["TitleFunctions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Elenco Procedure")]
        public string TitleProcedures {
            get {
                return ((string)(this["TitleProcedures"]));
            }
            set {
                this["TitleProcedures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Elenco Trigger")]
        public string TitleTriggers {
            get {
                return ((string)(this["TitleTriggers"]));
            }
            set {
                this["TitleTriggers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Elenco Viste")]
        public string TitleViews {
            get {
                return ((string)(this["TitleViews"]));
            }
            set {
                this["TitleViews"] = value;
            }
        }
    }
}
