//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportSQL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExportSQL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estrazione dei trigger....
        /// </summary>
        internal static string WizardForm_export_Estrazione_dei_trigger {
            get {
                return ResourceManager.GetString("WizardForm_export_Estrazione_dei_trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estrazione delle funzioni....
        /// </summary>
        internal static string WizardForm_export_Estrazione_delle_funzioni {
            get {
                return ResourceManager.GetString("WizardForm_export_Estrazione_delle_funzioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estrazione delle procedure....
        /// </summary>
        internal static string WizardForm_export_Estrazione_delle_procedure {
            get {
                return ResourceManager.GetString("WizardForm_export_Estrazione_delle_procedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estrazione delle viste....
        /// </summary>
        internal static string WizardForm_export_Estrazione_delle_viste {
            get {
                return ResourceManager.GetString("WizardForm_export_Estrazione_delle_viste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estrazione delle viste....
        /// </summary>
        internal static string WizardForm_export_Estrazione_delle_viste___ {
            get {
                return ResourceManager.GetString("WizardForm_export_Estrazione_delle_viste___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operazione completata con successo.
        /// </summary>
        internal static string WizardForm_export_Operazione_completata_con_successo {
            get {
                return ResourceManager.GetString("WizardForm_export_Operazione_completata_con_successo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvataggio....
        /// </summary>
        internal static string WizardForm_export_Salvataggio {
            get {
                return ResourceManager.GetString("WizardForm_export_Salvataggio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione.
        /// </summary>
        internal static string WizardForm_validate_Attenzione {
            get {
                return ResourceManager.GetString("WizardForm_validate_Attenzione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore.
        /// </summary>
        internal static string WizardForm_validate_Errore {
            get {
                return ResourceManager.GetString("WizardForm_validate_Errore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scegliere almeno un tipo di oggetto!.
        /// </summary>
        internal static string WizardForm_validate_Scegliere_almeno_un_tipo_di_oggetto_ {
            get {
                return ResourceManager.GetString("WizardForm_validate_Scegliere_almeno_un_tipo_di_oggetto_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scegliere un file esistente e valido!.
        /// </summary>
        internal static string WizardForm_validate_Scegliere_un_file_esistente_e_valido {
            get {
                return ResourceManager.GetString("WizardForm_validate_Scegliere_un_file_esistente_e_valido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scegliere una cartella esistente e valida!.
        /// </summary>
        internal static string WizardForm_validate_Scegliere_una_cartella_esistente_e_valida {
            get {
                return ResourceManager.GetString("WizardForm_validate_Scegliere_una_cartella_esistente_e_valida", resourceCulture);
            }
        }
    }
}
